const fs = require('fs');
const p = require('path').join(__dirname, '..', 'src', 'index.css');
const a = (s) => fs.appendFileSync(p, s);
a('\n');
a('.debug-terminal { position: fixed; top: 0; left: 0; bottom: 0; width: 320px; max-width: 85vw; background: linear-gradient(180deg, rgba(10, 14, 28, 0.95), rgba(7, 9, 19, 0.98)); backdrop-filter: blur(24px); -webkit-backdrop-filter: blur(24px); border-right: 1px solid rgba(0, 243, 255, 0.15); z-index: 50; display: flex; flex-direction: column; font-family: \'JetBrains Mono\', \'Fira Code\', monospace; font-size: 0.7rem; box-shadow: 4px 0 30px rgba(0, 0, 0, 0.6), 0 0 60px rgba(0, 243, 255, 0.05); transform: translateX(-100%); transition: transform 0.4s cubic-bezier(0.4, 0, 0.2, 1); overflow: hidden; }\n');
a('.debug-terminal.open { transform: translateX(0); }\n');
a('.debug-terminal::before { content: \'\'; position: absolute; top: 0; left: 0; right: 0; height: 100%; background: repeating-linear-gradient(0deg, transparent 0px, transparent 2px, rgba(0, 243, 255, 0.02) 2px, rgba(0, 243, 255, 0.02) 4px); pointer-events: none; z-index: 1; }\n');
a('.debug-terminal-header { display: flex; justify-content: space-between; align-items: center; padding: 0.75rem 1rem; border-bottom: 1px solid rgba(0, 243, 255, 0.15); flex-shrink: 0; }\n');
a('.debug-terminal-title { font-weight: 800; text-transform: uppercase; letter-spacing: 2px; color: var(--neon-cyan); font-size: 0.75rem; display: flex; align-items: center; gap: 0.4rem; }\n');
a('.debug-terminal-close { background: none; border: 1px solid rgba(255, 42, 109, 0.3); color: var(--text-muted); cursor: pointer; font-size: 0.9rem; padding: 0.2rem 0.4rem; border-radius: 6px; transition: all 0.2s ease; line-height: 1; }\n');
a('.debug-terminal-close:hover { border-color: var(--neon-red); color: var(--neon-red); background: rgba(255, 42, 109, 0.1); }\n');
a('.debug-terminal-body { flex: 1; overflow-y: auto; padding: 0.75rem; display: flex; flex-direction: column; gap: 0.6rem; }\n');
a('.debug-terminal-body::-webkit-scrollbar { width: 4px; }\n');
a('.debug-terminal-body::-webkit-scrollbar-track { background: transparent; }\n');
a('.debug-terminal-body::-webkit-scrollbar-thumb { background: rgba(0, 243, 255, 0.2); border-radius: 2px; }\n');
a('\n');
a('.debug-section { display: flex; flex-direction: column; gap: 0.35rem; }\n');
a('.debug-section-title { font-size: 0.6rem; font-weight: 800; text-transform: uppercase; letter-spacing: 1.5px; color: var(--text-muted); padding-bottom: 0.2rem; border-bottom: 1px solid rgba(255, 255, 255, 0.06); }\n');
a('.debug-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 0.3rem; }\n');
a('.debug-item { display: flex; flex-direction: column; gap: 0.1rem; padding: 0.35rem 0.45rem; background: rgba(0, 243, 255, 0.03); border-radius: 8px; border: 1px solid rgba(0, 243, 255, 0.06); transition: all 0.2s ease; }\n');
a('.debug-item:hover { background: rgba(0, 243, 255, 0.06); border-color: rgba(0, 243, 255, 0.12); }\n');
a('.debug-item.full-width { grid-column: 1 / -1; }\n');
a('.debug-label { font-size: 0.55rem; font-weight: 700; color: var(--text-muted); text-transform: uppercase; letter-spacing: 0.5px; }\n');
a('.debug-value { font-weight: 700; color: var(--text-main); font-size: 0.8rem; }\n');
a('.debug-value.good { color: var(--neon-green); }\n');
a('.debug-value.warn { color: var(--neon-amber); }\n');
a('.debug-value.bad { color: var(--neon-red); }\n');
a('.debug-value.highlight { color: var(--neon-cyan); font-weight: 900; }\n');
a('.debug-badge { display: inline-flex; align-items: center; gap: 0.25rem; padding: 0.15rem 0.5rem; border-radius: 50px; font-size: 0.6rem; font-weight: 800; text-transform: uppercase; letter-spacing: 0.5px; }\n');
a('.debug-badge.active { background: rgba(0, 255, 136, 0.12); border: 1px solid rgba(0, 255, 136, 0.3); color: var(--neon-green); }\n');
a('.debug-badge.inactive { background: rgba(148, 163, 184, 0.1); border: 1px solid rgba(148, 163, 184, 0.2); color: var(--text-muted); }\n');
a('.debug-badge.warning { background: rgba(255, 170, 0, 0.12); border: 1px solid rgba(255, 170, 0, 0.3); color: var(--neon-amber); }\n');
a('.debug-terminal-toggle { position: fixed; top: 5.5rem; left: 1rem; width: 40px; height: 40px; border-radius: 12px; border: 1px solid rgba(0, 243, 255, 0.25); background: rgba(16, 20, 38, 0.7); backdrop-filter: blur(16px); color: var(--neon-cyan); cursor: pointer; font-size: 1.1rem; display: flex; align-items: center; justify-content: center; z-index: 49; transition: all 0.3s ease; }\n');
a('.debug-terminal-toggle:hover { background: rgba(0, 243, 255, 0.15); border-color: var(--neon-cyan); box-shadow: 0 0 20px rgba(0, 243, 255, 0.3); }\n');
a('.debug-terminal-toggle.active { background: rgba(0, 243, 255, 0.2); border-color: var(--neon-cyan); }\n');
console.log('Chunk 8 done');
