const fs = require('fs');
const p = require('path').join(__dirname, '..', 'src', 'index.css');
const a = (s) => fs.appendFileSync(p, s);
a('\n');
a('.setup-guide-overlay { position: fixed; top: 0; left: 0; width: 100%; height: 100%; z-index: 12; pointer-events: none; display: flex; flex-direction: column; align-items: center; justify-content: center; }\n');
a('.setup-guide-canvas { position: absolute; top: 0; left: 0; width: 100%; height: 100%; pointer-events: none; }\n');
a('.setup-guide-warnings { position: absolute; bottom: 9rem; left: 50%; transform: translateX(-50%); display: flex; flex-direction: column; gap: 0.4rem; align-items: center; z-index: 20; }\n');
a('.setup-guide-title { font-size: 0.85rem; font-weight: 800; text-transform: uppercase; letter-spacing: 1.5px; color: var(--text-main); background: linear-gradient(135deg, rgba(16, 20, 38, 0.8), rgba(16, 20, 38, 0.6)); backdrop-filter: blur(16px); padding: 0.55rem 1.1rem; border-radius: 50px; border: 1px solid var(--glass-border); }\n');
a('.setup-chip { padding: 0.45rem 0.9rem; border-radius: 50px; font-size: 0.75rem; font-weight: 700; background: linear-gradient(135deg, rgba(16, 20, 38, 0.8), rgba(16, 20, 38, 0.6)); backdrop-filter: blur(16px); border: 1px solid var(--glass-border); transition: all 0.3s ease; }\n');
a('.setup-chip.ready { border-color: var(--neon-green); color: var(--neon-green); box-shadow: 0 0 15px rgba(0, 255, 136, 0.25); }\n');
a('.setup-chip.warn { border-color: var(--neon-amber); color: var(--neon-amber); box-shadow: 0 0 12px rgba(255, 170, 0, 0.2); }\n');
a('.setup-chip.hint { color: var(--text-muted); font-size: 0.7rem; }\n');
a('\n');
a('.pose-corrector-status { display: flex; align-items: center; gap: 0.4rem; padding: 0.4rem 0.85rem; background: linear-gradient(135deg, rgba(16, 20, 38, 0.75), rgba(16, 20, 38, 0.55)); backdrop-filter: blur(16px); border: 1px solid var(--glass-border); border-radius: 50px; font-size: 0.75rem; font-weight: 700; transition: all 0.3s ease; }\n');
a('.pose-corrector-dot { width: 9px; height: 9px; border-radius: 50%; background: var(--neon-green); box-shadow: 0 0 8px var(--neon-green); animation: pulse-glow 1.5s ease-in-out infinite; flex-shrink: 0; }\n');
a('.pose-corrector-dot.off { background: var(--text-muted); box-shadow: none; animation: none; }\n');
a('.pose-corrector-score { font-weight: 900; color: var(--neon-cyan); }\n');
a('.pose-corrector-label { color: var(--text-muted); font-size: 0.65rem; text-transform: uppercase; letter-spacing: 0.5px; }\n');
console.log('Chunk 7 done');
