const fs = require('fs');
const p = require('path').join(__dirname, '..', 'src', 'index.css');
const a = (s) => fs.appendFileSync(p, s);
a('\n');
a('.character-card::before, .character-card::after { content: \'\'; position: absolute; width: 18px; height: 18px; border-color: var(--neon-cyan); border-style: solid; opacity: 0.6; transition: opacity 0.3s ease; }\n');
a('.character-card::before { top: 6px; left: 6px; border-width: 2px 0 0 2px; }\n');
a('.character-card::after { bottom: 6px; right: 6px; border-width: 0 2px 2px 0; }\n');
a('.character-card:hover::before, .character-card:hover::after { opacity: 1; }\n');
a('.character-card:hover { border-color: rgba(0, 243, 255, 0.3); box-shadow: var(--glass-shadow), 0 0 40px rgba(0, 243, 255, 0.12); }\n');
a('\n');
a('.level-display { background: linear-gradient(135deg, var(--neon-cyan), var(--neon-purple)); border-radius: 14px; padding: 0.45rem 0.75rem; box-shadow: 0 0 15px rgba(0, 243, 255, 0.4); position: relative; flex-shrink: 0; }\n');
a('.level-display::after { content: \'\'; position: absolute; inset: -3px; border-radius: 16px; background: linear-gradient(135deg, var(--neon-cyan), var(--neon-purple)); opacity: 0.3; filter: blur(8px); z-index: -1; }\n');
a('.level-number { font-weight: 900; font-size: 1.15rem; color: #fff; letter-spacing: 0.5px; text-shadow: 0 0 10px rgba(255, 255, 255, 0.5); }\n');
a('\n');
a('.xp-bar-container { flex: 1; display: flex; flex-direction: column; gap: 0.3rem; min-width: 0; }\n');
a('.xp-bar-track { width: 100%; height: 8px; background: rgba(0, 243, 255, 0.06); border-radius: 4px; overflow: hidden; box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.6), 0 0 1px rgba(0, 243, 255, 0.2); position: relative; }\n');
a('.xp-bar-fill { height: 100%; background: linear-gradient(90deg, var(--neon-cyan), var(--neon-blue), var(--neon-purple)); background-size: 200% 100%; border-radius: 4px; transition: width 0.6s cubic-bezier(0.4, 0, 0.2, 1); box-shadow: 0 0 12px var(--neon-cyan); animation: xp-shimmer 2.5s ease-in-out infinite; }\n');
a('@keyframes xp-shimmer { 0%, 100% { background-position: 0% 50%; } 50% { background-position: 100% 50%; } }\n');
a('.xp-bar-label { font-size: 0.65rem; font-weight: 700; color: var(--text-muted); letter-spacing: 0.5px; display: flex; justify-content: space-between; }\n');
a('.xp-bar-label span:last-child { color: var(--neon-cyan); opacity: 0.8; }\n');
a('\n');
a('.resource-bar { display: flex; gap: 0.5rem; align-items: center; }\n');
a('.resource-item { display: flex; align-items: center; gap: 0.3rem; background: rgba(255, 215, 0, 0.06); border: 1px solid rgba(255, 215, 0, 0.2); border-radius: 12px; padding: 0.35rem 0.6rem; font-size: 0.7rem; font-weight: 800; color: var(--neon-gold); letter-spacing: 0.5px; transition: all 0.25s ease; }\n');
a('.resource-item:hover { background: rgba(255, 215, 0, 0.12); border-color: rgba(255, 215, 0, 0.4); }\n');
a('.resource-icon { font-size: 0.9rem; filter: drop-shadow(0 0 4px rgba(255, 215, 0, 0.5)); }\n');
console.log('Chunk 1 done');
